# Generated by Django 2.2.6 on 2021-06-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('fin_date', models.DateTimeField()),
                ('types', models.CharField(choices=[('H', 'Высокий'), ('M', 'Средний'), ('L', 'Низкий')], max_length=200)),
                ('status', models.CharField(choices=[('W', 'Ожидает выполнения'), ('C', 'Выполнена'), ('I', 'В процессе выполнения')], default='W', max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Задача',
                'ordering': ['-pub_date'],
            },
        ),
    ]
